### ISSUE TITLE
Customui broken in 110.0b4

### ISSUE THREAD

**Issue by tatankat** [rsjtdrjgfuzkfg/thunderbird-experiments#10]
customui seems broken in the latest beta TB 110.0b4 (at least it broke somewhere between 102.8.0 and 110.0b4)

Calling
```
        messenger.ex_customui.add(
          messenger.ex_customui.LOCATION_MESSAGING,
          htmlPage,
          { width }
        );
```
this line https://github.com/rsjtdrjgfuzkfg/thunderbird-experiments/blob/1e321c64e2b0f854d061f973ed255d54e5f740ba/experiments/customui/parent.js#L199 throws following errors:
```
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“default-src”). 2 [customElements.js:500:24](chrome://global/content/customElements.js)
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“default-src”). [panel.js:62:22](chrome://global/content/elements/panel.js)
```
and no sidebar is shown.

**Comment by rsjtdrjgfuzkfg** [comment]
I don't plan to properly investigate this until the ESR gets closer (I don't support beta versions), but from a first glance this seems to be a Thunderbird bug (creating an adding `browser` element fails due to CSR, in two places of mozilla-central code, the first one being https://searchfox.org/mozilla-central/source/toolkit/content/customElements.js#500). @jobisoft might know more if this came up in other extensions that are compatible with beta.

**Comment by rsjtdrjgfuzkfg** [comment]
I assume this is fixed with the latest beta versions of Thunderbird and 3c1f7ecfb4025887b2b11140067ee7e78d50997f, at least my tests work now. Let me know if you still see the issue.

Note that sidebars can no longer be resized by the user and have some visual glitches when resizing from code. I'm happy to accept PRs addressing these issues, but as my add-ons don't use sidebars at all and as customui no longer has a path to becoming a core API I have no plans to further improve things myself.
