### ISSUE TITLE
Is cachingFix still usable in TB128?

### ISSUE THREAD

**Issue by jobisoft** [rsjtdrjgfuzkfg/thunderbird-experiments#14]
I am no longer able to load modules using file://- or jar://-URLs in TB128, only resource:// urls (probably also chrome://).

Can you confirm this? This would mean the Experiment can no longer be used in 128+, right?

**Comment by rsjtdrjgfuzkfg** [comment]
In the private codebase of GeneralSync I indeed switched away from that experiment due to Thunderbird 102 (!) not supporting anything but resource:// and chrome:// URIs, at least according to my commit messages from back then.

You're correct, it is probably a good idea to remove it now (or yesterday ;) ).

**Comment by jobisoft** [comment]
I have removed it from DTN as well. Thanks for your feedback and your support.
